process.loadEnvFile();
// import express from 'express';
// import fetch from 'node-fetch';
// const app = express();
import http from "node:http";
import url from "node:url"
const PORT = 3000;

//Main function to be called for fetching data from Instana
/**
 * 
 * @param {Date} toDate 
 * @param {Number} timeFrame 
 * @param {String} appName 
 * @param {String} serviceName 
 * @returns {Array} metrics
 */
async function fetchInstanaData(toDate, timeFrame, tagFilterExpression, response) {
    //Getting API Token + API URL from env and generating endpoint
    const API_TOKEN = process.env.INSTANA_API_KEY;
    const INSTANA_API_URL = process.env.INSTANA_REPORTING_URL;
    const endpoint = `${INSTANA_API_URL}/application-monitoring/analyze/call-groups`;

    //Creating an abort controller to deal with timeouts
    const HTTP_TIMEOUT = 90000;
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), HTTP_TIMEOUT);

    //Try will actually do the fetch; requires method = POST, headers for auth and content-type, body generated by function
    //Pass arguments from fetchInstanaData to generateInstanaBody to get specific 
    try {
        let res = await fetch(endpoint, {
            method: "POST",
            headers: {
                "Authorization": `apiToken ${API_TOKEN}`,
                "Content-Type": "application/json"
            },
            body: generateInstanaBody(toDate, timeFrame, tagFilterExpression),
            signal: controller.signal,
            //cache: "no-cache"
        });

        if (!res.ok) {
            throw new Error(`HTTP error! Status: ${res.message.status}`);
        }

        let data = await res.json();

        response.writeHead(200, {'Content-Type': 'application/json'});
        response.write(JSON.stringify(data));

    } catch (error) {
        console.error('Proxy Error: ', error);
        response.write({error: 'Failed to fetch data from Instana'});
    } finally {
        response.end();
        clearTimeout(timeoutId);
    }
}


//Generates the JSON Tree which will be used for the body
/**
 * Converts toDate and timeFrame to milliseconds which is the requirement for Instana Body
 * @param {Date} toDate 
 * @param {Number} timeFrame 
 * @param {String} appName 
 * @param {String} serviceName 
 * @returns {String} body
 */
function generateInstanaBody(toDate, timeFrame, tagFilterExpression) {
    let body = {
        "timeFrame": {
            "to": toDate,
            "windowSize": timeFrame,
            "focusedMoment": toDate,
            "autoRefresh": false
        },
        "tagFilterExpression": tagFilterExpression,
        "metrics": [
            {
                "metric": "calls",
                "aggregation": "SUM"
            },
            {
                "metric": "errors",
                "aggregation": "MEAN"
            },
            {
                "metric": "latency",
                "aggregation": "MEAN"
            }
        ],
        "order": {
            "by": "calls",
            "direction": "DESC"
        },
        "group": {
            "groupbyTag": "call.name",
            "tagType": "STRING"
        },
        "includeSynthetic": true
    };



    return JSON.stringify(body);
}

// //Proxy server with headers to avoid CORS errors
// app.get('/proxy', async (req, res) => {
//     res.header("Access-Control-Allow-Origin", "*");
//     res.header("Access-Control-Allow-Headers", "X-Requested-With");
//     let toDate = req.query.toDate;
//     let timeFrame = req.query.timeFrame;
//     let tagFilterExpression = JSON.parse(decodeURIComponent(req.query.filterData));
//     fetchInstanaData(toDate, timeFrame, tagFilterExpression, res);
// });

// app.listen(PORT, () => {
//     console.log(`Proxy server running at http://localhost:${PORT}`);
// });

const server = http.createServer(async (req, res) => {
    // Parse the URL and query parameters
    const parsedUrl = url.parse(req.url, true);
    const pathname = parsedUrl.pathname;
    const query = parsedUrl.query;

    // Handle the specific '/proxy' route and GET method
    if (pathname === '/proxy' && req.method === 'GET') {
        // Set necessary headers
        res.setHeader('Access-Control-Allow-Origin', '*');
        res.setHeader('Access-Control-Allow-Headers', 'X-Requested-With');

        // Extract query parameters
        let toDate = query.toDate;
        let timeFrame = query.timeFrame;
        
        let tagFilterExpression;
        try {
            // Decode and parse filterData
            tagFilterExpression = JSON.parse(decodeURIComponent(query.filterData));
        } catch (e) {
            // Handle parsing errors gracefully
            res.writeHead(400, { 'Content-Type': 'text/plain' });
            res.end('Invalid filterData format');
            return;
        }

        // Call the data fetching function (ensure fetchInstanaData is defined in scope)
        // You need to ensure fetchInstanaData handles the 'res' object correctly (e.g., sending the response back)
        fetchInstanaData(toDate, timeFrame, tagFilterExpression, res);

    } else {
        // Handle other routes or methods (optional)
        res.writeHead(404, { 'Content-Type': 'text/plain' });
        res.end('Not Found');
    }
});

server.listen(PORT, () => {
    console.log(`Proxy server running at http://localhost:${PORT}`);
});